name: Deploy GraphRAG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH tools
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass

    - name: Deploy to Remote Server
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          # Clone or update the repository
          if [ ! -d "GraphRAG" ]; then
            git clone https://github.com/fatemenajafi135/GraphRAG.git
          fi
          cd GraphRAG
          git pull

          # Ensure environment variables are available
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

          # Deploy with Docker Compose
          docker-compose down
          docker-compose up --build -d
        EOF

    - name: Verify Deployment
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "docker ps"
